[RemoteStartUnit.X2Ability_UnitRemoteStart]
+UnitRemoteStartEntries=(Unit="AdvPurifierM1",Radius=4.0,Damage=(Damage=6,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=16)
+UnitRemoteStartEntries=(Unit="AdvPurifierM2",Radius=6.0,Damage=(Damage=8,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=16)
+UnitRemoteStartEntries=(Unit="AdvPurifierM3",Radius=8.0,Damage=(Damage=10,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=16)

; Support for Purifier Revamp
+UnitRemoteStartEntries=(Unit="AdvPurifierCaptainM1",Radius=8.0,Damage=(Damage=9,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=18)
+UnitRemoteStartEntries=(Unit="AdvPurifierCaptainM2",Radius=10.0,Damage=(Damage=11,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=18)
+UnitRemoteStartEntries=(Unit="AdvPurifierCaptainM3",Radius=12.0,Damage=(Damage=13,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=18)

; Support for Frost Legion
+UnitRemoteStartEntries=(Unit="FrostPurifier_M1",Radius=4.0,Damage=(Damage=6,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="frost"),EnvDamage=16)
+UnitRemoteStartEntries=(Unit="FrostPurifier_M2",Radius=6.0,Damage=(Damage=8,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="frost"),EnvDamage=16)
+UnitRemoteStartEntries=(Unit="FrostPurifier_M3",Radius=8.0,Damage=(Damage=10,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="frost"),EnvDamage=16)

; Support for A Requiem For Man: ADVENT Pack
+UnitRemoteStartEntries=(Unit="ARFMAdvTorcherM1",Radius=4.0,Damage=(Damage=6,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=16)
+UnitRemoteStartEntries=(Unit="ARFMAdvTorcherM2",Radius=6.0,Damage=(Damage=8,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=16)
+UnitRemoteStartEntries=(Unit="ARFMAdvTorcherM3",Radius=8.0,Damage=(Damage=10,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=16)

;* Add more units to the list
;+UnitRemoteStartEntries=(Unit="sectoid",Radius=3.0,Damage=(Damage=2,Spread=1,PlusOne=50,Crit=0,Pierce=0,Shred=1,Tag="",DamageType="Explosion"),EnvDamage=16)

UnitRemoteStartActionPointCost = 1
UnitRemoteStartConsumeAllActionPoints = true
UnitRemoteStartAmmoCost = 1
UnitRemoteStartCooldown = 2

[RemoteStartUnit.X2DLCInfo_RemoteStartUnit]

;* Add the names of any abilities you want to have the "remote start unit" ability added.
+AbilitiesToCheckForRemoteStartAddition="RemoteStart"

; Support for Immolator Chemthrower
+AbilitiesToCheckForRemoteStartAddition="Fulmination"

; Support for Frost Legion
+AbilitiesToCheckForRemoteStartAddition="MZFD_RemoteStart"

; Support for Proficiency Pack
+AbilitiesToCheckForRemoteStartAddition="WOTC_APA_RemoteStart"

; Support for Faction Hero Sitrep
+AbilitiesToCheckForRemoteStartAddition="RhiRemoteFuse"

; Support for Savage Sitrep Core
+AbilitiesToCheckForRemoteStartAddition="SAVRemoteStart"
